[tool.poetry]
name = "autofmu"
version = "0.1.0"
description = "Automatic FMU approximation tool"
authors = ["Afonso Cerejeira <ajcerejeira@gmail.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/ajcerejeira/autofmu"
repository = "https://github.com/ajcerejeira/autofmu"
documentation = "https://autofmu.readthedocs.io/"
keywords = [
    "fmi",
    "functional mockup interface",
    "fmu",
    "functional mockup unit",
    "machine learning"
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Manufacturing",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: C",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Software Development :: Compilers",
    "Typing :: Typed"
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/ajcerejeira/autofmu/issues"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
isort = "^4.3.21"
flake8 = "^3.8.3"
flake8-bugbear = "^20.1.4"
flake8-bandit = "^2.1.2"
flake8-docstrings = "^1.5.0"
flake8-rst-docstrings = "^0.0.13"
pep8-naming = "^0.10.0"
doc8 = "^0.8.1"
sphinx = "^3.1.1"
sphinx_rtd_theme = "^0.4.3"
sphinx-argparse = "^0.2.5"
sphinx-autodoc-typehints = "^1.10.3"
mypy = "^0.780"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
