name: Coverage

on: push

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: pip install nox
    - run: nox -s test-3.8
    - uses: codecov/codecov-action@v1
